#!/usr/bin/env bash
set -euo pipefail

: "${GCP_PROJECT_ID:?Set GCP_PROJECT_ID}"
: "${GCP_REGION:?Set GCP_REGION}"
: "${GAR_REPOSITORY:?Set GAR_REPOSITORY}"
: "${SERVICE_NAME:=lien-automation}"
: "${IMAGE_URI:?Set IMAGE_URI}"
: "${GIT_SHA:=unknown}"
: "${SHEET_ID:?Set SHEET_ID}"
: "${MERGED_SHEET_ID:=1qa32AEUMC4TYHh4G6AV4msRS4GjQQZFTNPpYHMh4n5A}"
: "${DATABASE_URL_SECRET_REF:?Set DATABASE_URL_SECRET_REF}"
: "${SCHEDULE_RUN_TOKEN_SECRET_REF:?Set SCHEDULE_RUN_TOKEN_SECRET_REF}"
: "${SHEETS_KEY_SECRET_REF:?Set SHEETS_KEY_SECRET_REF}"
: "${SBR_CDP_URL_SECRET_REF:?Set SBR_CDP_URL_SECRET_REF}"
: "${LEAD_ALERT_WEBHOOK_URL_SECRET_REF:=}"
: "${CLOUDSQL_INSTANCE_CONNECTION_NAME:=}"
: "${BRIGHTDATA_BROWSER_WS:=}"
: "${BRIGHTDATA_PROXY_SERVER:=}"
: "${BRIGHTDATA_PROXY_USERNAME:=}"
: "${BRIGHTDATA_PROXY_PASSWORD:=}"
: "${DRY_RUN:=0}"
: "${LEAD_ALERT_EMAIL_TO:=antigravity1@timberlinetax.com}"
: "${LEAD_ALERT_EMAIL_FROM:=}"
: "${LEAD_ALERT_WEBHOOK_URL:=}"
: "${LEAD_ALERT_RESEND_API_KEY:=}"
: "${SCHEDULE_ALERT_WEBHOOK_URL:=}"
: "${REVIEW_QUEUE_RETENTION_DAYS:=7}"

: "${SCHEDULE_CA_SOS_TIMEZONE:=America/New_York}"
: "${SCHEDULE_CA_SOS_WEEKLY_DAYS:=MO,TU,WE,TH,FR,SA,SU}"
: "${SCHEDULE_CA_SOS_RUN_HOUR:=9}"
: "${SCHEDULE_CA_SOS_RUN_MINUTE:=0}"
: "${SCHEDULE_CA_SOS_DEADLINE_HOUR:=13}"
: "${SCHEDULE_CA_SOS_DEADLINE_MINUTE:=0}"
: "${SCHEDULE_CA_SOS_MAX_RECORDS:=1000}"
: "${SCHEDULE_NYC_ACRIS_TIMEZONE:=America/New_York}"
: "${SCHEDULE_NYC_ACRIS_WEEKLY_DAYS:=MO,TU,WE,TH,FR,SA,SU}"
: "${SCHEDULE_NYC_ACRIS_RUN_HOUR:=14}"
: "${SCHEDULE_NYC_ACRIS_RUN_MINUTE:=0}"
: "${SCHEDULE_NYC_ACRIS_DEADLINE_HOUR:=18}"
: "${SCHEDULE_NYC_ACRIS_DEADLINE_MINUTE:=0}"
: "${SCHEDULE_NYC_ACRIS_MAX_RECORDS:=5}"
: "${ACRIS_INITIAL_MAX_RECORDS:=5}"
: "${ACRIS_INITIAL_MAX_RESULT_PAGES:=1}"
: "${AMOUNT_MIN_COVERAGE_PCT:=95}"
: "${SCHEDULE_AUTO_THROTTLE:=1}"
: "${SCHEDULE_MAX_RECORDS:=1000}"
: "${SCHEDULE_MAX_RECORDS_FLOOR:=25}"
: "${SCHEDULE_MAX_RECORDS_CEILING:=400}"
: "${REQUIRE_OCR_TOOLS:=1}"

ENV_VARS_FILE="$(mktemp)"
cleanup() {
  rm -f "${ENV_VARS_FILE}"
}
trap cleanup EXIT

cat > "${ENV_VARS_FILE}" <<EOF
BRIGHTDATA_BROWSER_WS: '${BRIGHTDATA_BROWSER_WS}'
BRIGHTDATA_PROXY_SERVER: '${BRIGHTDATA_PROXY_SERVER}'
BRIGHTDATA_PROXY_USERNAME: '${BRIGHTDATA_PROXY_USERNAME}'
BRIGHTDATA_PROXY_PASSWORD: '${BRIGHTDATA_PROXY_PASSWORD}'
SHEET_ID: '${SHEET_ID}'
MERGED_SHEET_ID: '${MERGED_SHEET_ID}'
GIT_SHA: '${GIT_SHA}'
LEAD_ALERT_EMAIL_TO: '${LEAD_ALERT_EMAIL_TO}'
LEAD_ALERT_EMAIL_FROM: '${LEAD_ALERT_EMAIL_FROM}'
LEAD_ALERT_WEBHOOK_URL: '${LEAD_ALERT_WEBHOOK_URL}'
LEAD_ALERT_RESEND_API_KEY: '${LEAD_ALERT_RESEND_API_KEY}'
SCHEDULE_ALERT_WEBHOOK_URL: '${SCHEDULE_ALERT_WEBHOOK_URL}'
REVIEW_QUEUE_RETENTION_DAYS: '${REVIEW_QUEUE_RETENTION_DAYS}'
SCHEDULE_CA_SOS_TIMEZONE: '${SCHEDULE_CA_SOS_TIMEZONE}'
SCHEDULE_CA_SOS_WEEKLY_DAYS: '${SCHEDULE_CA_SOS_WEEKLY_DAYS}'
SCHEDULE_CA_SOS_RUN_HOUR: '${SCHEDULE_CA_SOS_RUN_HOUR}'
SCHEDULE_CA_SOS_RUN_MINUTE: '${SCHEDULE_CA_SOS_RUN_MINUTE}'
SCHEDULE_CA_SOS_DEADLINE_HOUR: '${SCHEDULE_CA_SOS_DEADLINE_HOUR}'
SCHEDULE_CA_SOS_DEADLINE_MINUTE: '${SCHEDULE_CA_SOS_DEADLINE_MINUTE}'
SCHEDULE_CA_SOS_MAX_RECORDS: '${SCHEDULE_CA_SOS_MAX_RECORDS}'
SCHEDULE_NYC_ACRIS_TIMEZONE: '${SCHEDULE_NYC_ACRIS_TIMEZONE}'
SCHEDULE_NYC_ACRIS_WEEKLY_DAYS: '${SCHEDULE_NYC_ACRIS_WEEKLY_DAYS}'
SCHEDULE_NYC_ACRIS_RUN_HOUR: '${SCHEDULE_NYC_ACRIS_RUN_HOUR}'
SCHEDULE_NYC_ACRIS_RUN_MINUTE: '${SCHEDULE_NYC_ACRIS_RUN_MINUTE}'
SCHEDULE_NYC_ACRIS_DEADLINE_HOUR: '${SCHEDULE_NYC_ACRIS_DEADLINE_HOUR}'
SCHEDULE_NYC_ACRIS_DEADLINE_MINUTE: '${SCHEDULE_NYC_ACRIS_DEADLINE_MINUTE}'
SCHEDULE_NYC_ACRIS_MAX_RECORDS: '${SCHEDULE_NYC_ACRIS_MAX_RECORDS}'
ACRIS_INITIAL_MAX_RECORDS: '${ACRIS_INITIAL_MAX_RECORDS}'
ACRIS_INITIAL_MAX_RESULT_PAGES: '${ACRIS_INITIAL_MAX_RESULT_PAGES}'
AMOUNT_MIN_COVERAGE_PCT: '${AMOUNT_MIN_COVERAGE_PCT}'
SCHEDULE_AUTO_THROTTLE: '${SCHEDULE_AUTO_THROTTLE}'
SCHEDULE_MAX_RECORDS: '${SCHEDULE_MAX_RECORDS}'
SCHEDULE_MAX_RECORDS_FLOOR: '${SCHEDULE_MAX_RECORDS_FLOOR}'
SCHEDULE_MAX_RECORDS_CEILING: '${SCHEDULE_MAX_RECORDS_CEILING}'
REQUIRE_OCR_TOOLS: '${REQUIRE_OCR_TOOLS}'
EOF

SECRET_ENVS="DATABASE_URL=${DATABASE_URL_SECRET_REF},SCHEDULE_RUN_TOKEN=${SCHEDULE_RUN_TOKEN_SECRET_REF},SHEETS_KEY=${SHEETS_KEY_SECRET_REF},SBR_CDP_URL=${SBR_CDP_URL_SECRET_REF}"
if [[ -n "${LEAD_ALERT_WEBHOOK_URL_SECRET_REF}" ]]; then
  SECRET_ENVS+=",LEAD_ALERT_WEBHOOK_URL=${LEAD_ALERT_WEBHOOK_URL_SECRET_REF}"
fi

REMOVE_ENV_VARS=(
  DATABASE_URL
  SCHEDULE_RUN_TOKEN
  SHEETS_KEY
  SBR_CDP_URL
)

REMOVE_SECRETS=(
  SCHEDULE_ALERT_WEBHOOK_URL
)

if [[ -n "${LEAD_ALERT_WEBHOOK_URL_SECRET_REF}" ]]; then
  REMOVE_ENV_VARS+=(LEAD_ALERT_WEBHOOK_URL)
else
  REMOVE_SECRETS+=(LEAD_ALERT_WEBHOOK_URL)
fi

DEPLOY_ARGS=(
  --project="${GCP_PROJECT_ID}"
  --region="${GCP_REGION}"
  --image="${IMAGE_URI}"
  --platform=managed
  --allow-unauthenticated
  --port=8080
  --env-vars-file="${ENV_VARS_FILE}"
  --set-secrets="${SECRET_ENVS}"
)

if [[ "${#REMOVE_ENV_VARS[@]}" -gt 0 ]]; then
  DEPLOY_ARGS+=(--remove-env-vars="$(IFS=,; echo "${REMOVE_ENV_VARS[*]}")")
fi

if [[ "${#REMOVE_SECRETS[@]}" -gt 0 ]]; then
  DEPLOY_ARGS+=(--remove-secrets="$(IFS=,; echo "${REMOVE_SECRETS[*]}")")
fi

if [[ -n "${CLOUDSQL_INSTANCE_CONNECTION_NAME}" ]]; then
  DEPLOY_ARGS+=(--add-cloudsql-instances="${CLOUDSQL_INSTANCE_CONNECTION_NAME}")
fi

if [[ "${DRY_RUN}" == "1" ]]; then
  echo "Dry run: Cloud Run deploy arguments validated for ${SERVICE_NAME}"
  printf '%s\n' \
    "project=${GCP_PROJECT_ID}" \
    "region=${GCP_REGION}" \
    "image=${IMAGE_URI}" \
    "service=${SERVICE_NAME}" \
    "env_vars_file=${ENV_VARS_FILE}" \
    "secret_envs=DATABASE_URL,SCHEDULE_RUN_TOKEN,SHEETS_KEY,SBR_CDP_URL" \
    "remove_env_vars=$(IFS=,; echo "${REMOVE_ENV_VARS[*]}")" \
    "remove_secrets=$(IFS=,; echo "${REMOVE_SECRETS[*]}")" \
    "cloudsql_attached=$([[ -n "${CLOUDSQL_INSTANCE_CONNECTION_NAME}" ]] && echo true || echo false)"
  exit 0
fi

gcloud run deploy "${SERVICE_NAME}" \
  "${DEPLOY_ARGS[@]}"

echo "Deployed Cloud Run service: ${SERVICE_NAME}"
