#!/usr/bin/env bash
set -euo pipefail

: "${GCP_PROJECT_ID:?Set GCP_PROJECT_ID}"
: "${GCP_REGION:?Set GCP_REGION}"
: "${JOB_NAME:=lien-scraper-job}"
: "${IMAGE_URI:?Set IMAGE_URI, e.g. us-central1-docker.pkg.dev/<project>/<repo>/lien-automation:v1}"

# Required runtime env vars for the scraper job.
: "${SHEETS_KEY:?Set SHEETS_KEY}"
: "${SHEET_ID:?Set SHEET_ID}"
: "${BRIGHTDATA_BROWSER_WS:=}"
: "${BRIGHTDATA_PROXY_SERVER:=}"
: "${BRIGHTDATA_PROXY_USERNAME:=}"
: "${BRIGHTDATA_PROXY_PASSWORD:=}"
: "${SBR_CDP_URL:=}"

# Optional tuning knobs.
: "${JOB_LOOKBACK_DAYS:=7}"
: "${JOB_MAX_RECORDS:=25}"
: "${TASK_TIMEOUT:=3600s}"
: "${MAX_RETRIES:=2}"

: "${SCHEDULE_CA_SOS_TIMEZONE:=America/New_York}"
: "${SCHEDULE_CA_SOS_WEEKLY_DAYS:=TU,WE}"
: "${SCHEDULE_CA_SOS_RUN_HOUR:=9}"
: "${SCHEDULE_CA_SOS_RUN_MINUTE:=0}"
: "${SCHEDULE_CA_SOS_DEADLINE_HOUR:=13}"
: "${SCHEDULE_CA_SOS_DEADLINE_MINUTE:=0}"
: "${SCHEDULE_CA_SOS_MAX_RECORDS:=1000}"
: "${SCHEDULE_NYC_ACRIS_TIMEZONE:=America/New_York}"
: "${SCHEDULE_NYC_ACRIS_WEEKLY_DAYS:=TU,WE,TH,FR}"
: "${SCHEDULE_NYC_ACRIS_MORNING_RUN_HOUR:=10}"
: "${SCHEDULE_NYC_ACRIS_MORNING_RUN_MINUTE:=0}"
: "${SCHEDULE_NYC_ACRIS_AFTERNOON_RUN_HOUR:=14}"
: "${SCHEDULE_NYC_ACRIS_AFTERNOON_RUN_MINUTE:=0}"
: "${SCHEDULE_NYC_ACRIS_DEADLINE_HOUR:=18}"
: "${SCHEDULE_NYC_ACRIS_DEADLINE_MINUTE:=0}"
: "${SCHEDULE_NYC_ACRIS_MAX_RECORDS:=5}"
: "${AMOUNT_MIN_COVERAGE_PCT:=95}"
: "${SCHEDULE_AUTO_THROTTLE:=1}"
: "${SCHEDULE_MAX_RECORDS_FLOOR:=25}"
: "${SCHEDULE_MAX_RECORDS_CEILING:=1000}"
: "${REQUIRE_OCR_TOOLS:=1}"
: "${ACRIS_INITIAL_MAX_RECORDS:=5}"
: "${ACRIS_INITIAL_MAX_RESULT_PAGES:=1}"

ENV_VARS="SBR_CDP_URL=${SBR_CDP_URL},BRIGHTDATA_BROWSER_WS=${BRIGHTDATA_BROWSER_WS},BRIGHTDATA_PROXY_SERVER=${BRIGHTDATA_PROXY_SERVER},BRIGHTDATA_PROXY_USERNAME=${BRIGHTDATA_PROXY_USERNAME},BRIGHTDATA_PROXY_PASSWORD=${BRIGHTDATA_PROXY_PASSWORD},SHEETS_KEY=${SHEETS_KEY},SHEET_ID=${SHEET_ID},JOB_LOOKBACK_DAYS=${JOB_LOOKBACK_DAYS},JOB_MAX_RECORDS=${JOB_MAX_RECORDS},JOB_SITE=ca_sos,SCHEDULE_CA_SOS_TIMEZONE=${SCHEDULE_CA_SOS_TIMEZONE},SCHEDULE_CA_SOS_WEEKLY_DAYS=${SCHEDULE_CA_SOS_WEEKLY_DAYS},SCHEDULE_CA_SOS_RUN_HOUR=${SCHEDULE_CA_SOS_RUN_HOUR},SCHEDULE_CA_SOS_RUN_MINUTE=${SCHEDULE_CA_SOS_RUN_MINUTE},SCHEDULE_CA_SOS_DEADLINE_HOUR=${SCHEDULE_CA_SOS_DEADLINE_HOUR},SCHEDULE_CA_SOS_DEADLINE_MINUTE=${SCHEDULE_CA_SOS_DEADLINE_MINUTE},SCHEDULE_CA_SOS_MAX_RECORDS=${SCHEDULE_CA_SOS_MAX_RECORDS},SCHEDULE_NYC_ACRIS_TIMEZONE=${SCHEDULE_NYC_ACRIS_TIMEZONE},SCHEDULE_NYC_ACRIS_WEEKLY_DAYS=${SCHEDULE_NYC_ACRIS_WEEKLY_DAYS},SCHEDULE_NYC_ACRIS_MORNING_RUN_HOUR=${SCHEDULE_NYC_ACRIS_MORNING_RUN_HOUR},SCHEDULE_NYC_ACRIS_MORNING_RUN_MINUTE=${SCHEDULE_NYC_ACRIS_MORNING_RUN_MINUTE},SCHEDULE_NYC_ACRIS_AFTERNOON_RUN_HOUR=${SCHEDULE_NYC_ACRIS_AFTERNOON_RUN_HOUR},SCHEDULE_NYC_ACRIS_AFTERNOON_RUN_MINUTE=${SCHEDULE_NYC_ACRIS_AFTERNOON_RUN_MINUTE},SCHEDULE_NYC_ACRIS_DEADLINE_HOUR=${SCHEDULE_NYC_ACRIS_DEADLINE_HOUR},SCHEDULE_NYC_ACRIS_DEADLINE_MINUTE=${SCHEDULE_NYC_ACRIS_DEADLINE_MINUTE},SCHEDULE_NYC_ACRIS_MAX_RECORDS=${SCHEDULE_NYC_ACRIS_MAX_RECORDS},ACRIS_INITIAL_MAX_RECORDS=${ACRIS_INITIAL_MAX_RECORDS},ACRIS_INITIAL_MAX_RESULT_PAGES=${ACRIS_INITIAL_MAX_RESULT_PAGES},AMOUNT_MIN_COVERAGE_PCT=${AMOUNT_MIN_COVERAGE_PCT},SCHEDULE_AUTO_THROTTLE=${SCHEDULE_AUTO_THROTTLE},SCHEDULE_MAX_RECORDS_FLOOR=${SCHEDULE_MAX_RECORDS_FLOOR},SCHEDULE_MAX_RECORDS_CEILING=${SCHEDULE_MAX_RECORDS_CEILING},REQUIRE_OCR_TOOLS=${REQUIRE_OCR_TOOLS}"

gcloud run jobs deploy "${JOB_NAME}" \
  --project="${GCP_PROJECT_ID}" \
  --region="${GCP_REGION}" \
  --image="${IMAGE_URI}" \
  --command="npm" \
  --args="run,start:job" \
  --tasks=1 \
  --parallelism=1 \
  --task-timeout="${TASK_TIMEOUT}" \
  --max-retries="${MAX_RETRIES}" \
  --set-env-vars="${ENV_VARS}"

echo "Deployed Cloud Run Job: ${JOB_NAME}"
