#!/usr/bin/env bash
set -euo pipefail

: "${GCP_PROJECT_ID:?Set GCP_PROJECT_ID}"
: "${GCP_REGION:?Set GCP_REGION}"
: "${GAR_REPOSITORY:?Set GAR_REPOSITORY}"
: "${SERVICE_NAME:=lien-automation}"
: "${IMAGE_URI:?Set IMAGE_URI}"
: "${GIT_SHA:=unknown}"

: "${SHEETS_KEY:?Set SHEETS_KEY}"
: "${SHEET_ID:?Set SHEET_ID}"
: "${SCHEDULE_RUN_TOKEN:?Set SCHEDULE_RUN_TOKEN}"
: "${DATABASE_URL:=}"
: "${CLOUDSQL_INSTANCE_CONNECTION_NAME:=}"
: "${BRIGHTDATA_BROWSER_WS:=}"
: "${BRIGHTDATA_PROXY_SERVER:=}"
: "${BRIGHTDATA_PROXY_USERNAME:=}"
: "${BRIGHTDATA_PROXY_PASSWORD:=}"
: "${SBR_CDP_URL:=}"

: "${SCHEDULE_CA_SOS_TIMEZONE:=America/New_York}"
: "${SCHEDULE_CA_SOS_WEEKLY_DAYS:=TU,WE}"
: "${SCHEDULE_CA_SOS_RUN_HOUR:=9}"
: "${SCHEDULE_CA_SOS_RUN_MINUTE:=0}"
: "${SCHEDULE_CA_SOS_DEADLINE_HOUR:=13}"
: "${SCHEDULE_CA_SOS_DEADLINE_MINUTE:=0}"
: "${SCHEDULE_CA_SOS_MAX_RECORDS:=1000}"
: "${SCHEDULE_NYC_ACRIS_TIMEZONE:=America/New_York}"
: "${SCHEDULE_NYC_ACRIS_WEEKLY_DAYS:=TU,WE,TH,FR}"
: "${SCHEDULE_NYC_ACRIS_RUN_HOUR:=14}"
: "${SCHEDULE_NYC_ACRIS_RUN_MINUTE:=0}"
: "${SCHEDULE_NYC_ACRIS_DEADLINE_HOUR:=18}"
: "${SCHEDULE_NYC_ACRIS_DEADLINE_MINUTE:=0}"
: "${SCHEDULE_NYC_ACRIS_MAX_RECORDS:=5}"
: "${ACRIS_INITIAL_MAX_RECORDS:=5}"
: "${ACRIS_INITIAL_MAX_RESULT_PAGES:=1}"
: "${AMOUNT_MIN_COVERAGE_PCT:=95}"
: "${SCHEDULE_AUTO_THROTTLE:=1}"
: "${SCHEDULE_MAX_RECORDS:=1000}"
: "${SCHEDULE_MAX_RECORDS_FLOOR:=25}"
: "${SCHEDULE_MAX_RECORDS_CEILING:=400}"
: "${REQUIRE_OCR_TOOLS:=1}"

ENV_VARS_FILE="$(mktemp)"
cleanup() {
  rm -f "${ENV_VARS_FILE}"
}
trap cleanup EXIT

cat > "${ENV_VARS_FILE}" <<EOF
SBR_CDP_URL: '${SBR_CDP_URL}'
BRIGHTDATA_BROWSER_WS: '${BRIGHTDATA_BROWSER_WS}'
BRIGHTDATA_PROXY_SERVER: '${BRIGHTDATA_PROXY_SERVER}'
BRIGHTDATA_PROXY_USERNAME: '${BRIGHTDATA_PROXY_USERNAME}'
BRIGHTDATA_PROXY_PASSWORD: '${BRIGHTDATA_PROXY_PASSWORD}'
SHEETS_KEY: '${SHEETS_KEY}'
SHEET_ID: '${SHEET_ID}'
SCHEDULE_RUN_TOKEN: '${SCHEDULE_RUN_TOKEN}'
DATABASE_URL: '${DATABASE_URL}'
GIT_SHA: '${GIT_SHA}'
SCHEDULE_CA_SOS_TIMEZONE: '${SCHEDULE_CA_SOS_TIMEZONE}'
SCHEDULE_CA_SOS_WEEKLY_DAYS: '${SCHEDULE_CA_SOS_WEEKLY_DAYS}'
SCHEDULE_CA_SOS_RUN_HOUR: '${SCHEDULE_CA_SOS_RUN_HOUR}'
SCHEDULE_CA_SOS_RUN_MINUTE: '${SCHEDULE_CA_SOS_RUN_MINUTE}'
SCHEDULE_CA_SOS_DEADLINE_HOUR: '${SCHEDULE_CA_SOS_DEADLINE_HOUR}'
SCHEDULE_CA_SOS_DEADLINE_MINUTE: '${SCHEDULE_CA_SOS_DEADLINE_MINUTE}'
SCHEDULE_CA_SOS_MAX_RECORDS: '${SCHEDULE_CA_SOS_MAX_RECORDS}'
SCHEDULE_NYC_ACRIS_TIMEZONE: '${SCHEDULE_NYC_ACRIS_TIMEZONE}'
SCHEDULE_NYC_ACRIS_WEEKLY_DAYS: '${SCHEDULE_NYC_ACRIS_WEEKLY_DAYS}'
SCHEDULE_NYC_ACRIS_RUN_HOUR: '${SCHEDULE_NYC_ACRIS_RUN_HOUR}'
SCHEDULE_NYC_ACRIS_RUN_MINUTE: '${SCHEDULE_NYC_ACRIS_RUN_MINUTE}'
SCHEDULE_NYC_ACRIS_DEADLINE_HOUR: '${SCHEDULE_NYC_ACRIS_DEADLINE_HOUR}'
SCHEDULE_NYC_ACRIS_DEADLINE_MINUTE: '${SCHEDULE_NYC_ACRIS_DEADLINE_MINUTE}'
SCHEDULE_NYC_ACRIS_MAX_RECORDS: '${SCHEDULE_NYC_ACRIS_MAX_RECORDS}'
ACRIS_INITIAL_MAX_RECORDS: '${ACRIS_INITIAL_MAX_RECORDS}'
ACRIS_INITIAL_MAX_RESULT_PAGES: '${ACRIS_INITIAL_MAX_RESULT_PAGES}'
AMOUNT_MIN_COVERAGE_PCT: '${AMOUNT_MIN_COVERAGE_PCT}'
SCHEDULE_AUTO_THROTTLE: '${SCHEDULE_AUTO_THROTTLE}'
SCHEDULE_MAX_RECORDS: '${SCHEDULE_MAX_RECORDS}'
SCHEDULE_MAX_RECORDS_FLOOR: '${SCHEDULE_MAX_RECORDS_FLOOR}'
SCHEDULE_MAX_RECORDS_CEILING: '${SCHEDULE_MAX_RECORDS_CEILING}'
REQUIRE_OCR_TOOLS: '${REQUIRE_OCR_TOOLS}'
EOF

DEPLOY_ARGS=(
  --project="${GCP_PROJECT_ID}"
  --region="${GCP_REGION}"
  --image="${IMAGE_URI}"
  --platform=managed
  --allow-unauthenticated
  --port=8080
  --env-vars-file="${ENV_VARS_FILE}"
)

if [[ -n "${CLOUDSQL_INSTANCE_CONNECTION_NAME}" ]]; then
  DEPLOY_ARGS+=(--add-cloudsql-instances="${CLOUDSQL_INSTANCE_CONNECTION_NAME}")
fi

gcloud run deploy "${SERVICE_NAME}" \
  "${DEPLOY_ARGS[@]}"

echo "Deployed Cloud Run service: ${SERVICE_NAME}"
