#!/usr/bin/env bash
set -euo pipefail

: "${GCP_PROJECT_ID:?Set GCP_PROJECT_ID}"
: "${GCP_REGION:?Set GCP_REGION}"
: "${JOB_NAME:=lien-scraper-job}"
: "${IMAGE_URI:?Set IMAGE_URI, e.g. us-central1-docker.pkg.dev/<project>/<repo>/lien-automation:v1}"

# Required runtime env vars for the scraper job.
: "${SBR_CDP_URL:?Set SBR_CDP_URL}"
: "${SHEETS_KEY:?Set SHEETS_KEY}"
: "${SHEET_ID:?Set SHEET_ID}"

# Optional tuning knobs.
: "${JOB_LOOKBACK_DAYS:=7}"
: "${JOB_MAX_RECORDS:=25}"
: "${TASK_TIMEOUT:=3600s}"
: "${MAX_RETRIES:=2}"

: "${SCHEDULE_TARGET_TIMEZONE:=America/New_York}"
: "${SCHEDULE_WEEKLY_DAYS:=TU,WE}"
: "${SCHEDULE_RUN_HOUR:=9}"
: "${SCHEDULE_RUN_MINUTE:=0}"
: "${SCHEDULE_DEADLINE_HOUR:=13}"
: "${SCHEDULE_DEADLINE_MINUTE:=0}"
: "${AMOUNT_MIN_COVERAGE_PCT:=95}"
: "${SCHEDULE_AUTO_THROTTLE:=1}"
: "${SCHEDULE_MAX_RECORDS_FLOOR:=25}"
: "${SCHEDULE_MAX_RECORDS_CEILING:=1000}"
: "${REQUIRE_OCR_TOOLS:=1}"

ENV_VARS="SBR_CDP_URL=${SBR_CDP_URL},SHEETS_KEY=${SHEETS_KEY},SHEET_ID=${SHEET_ID},JOB_LOOKBACK_DAYS=${JOB_LOOKBACK_DAYS},JOB_MAX_RECORDS=${JOB_MAX_RECORDS},JOB_SITE=ca_sos,SCHEDULE_TARGET_TIMEZONE=${SCHEDULE_TARGET_TIMEZONE},SCHEDULE_WEEKLY_DAYS=${SCHEDULE_WEEKLY_DAYS},SCHEDULE_RUN_HOUR=${SCHEDULE_RUN_HOUR},SCHEDULE_RUN_MINUTE=${SCHEDULE_RUN_MINUTE},SCHEDULE_DEADLINE_HOUR=${SCHEDULE_DEADLINE_HOUR},SCHEDULE_DEADLINE_MINUTE=${SCHEDULE_DEADLINE_MINUTE},AMOUNT_MIN_COVERAGE_PCT=${AMOUNT_MIN_COVERAGE_PCT},SCHEDULE_AUTO_THROTTLE=${SCHEDULE_AUTO_THROTTLE},SCHEDULE_MAX_RECORDS_FLOOR=${SCHEDULE_MAX_RECORDS_FLOOR},SCHEDULE_MAX_RECORDS_CEILING=${SCHEDULE_MAX_RECORDS_CEILING},REQUIRE_OCR_TOOLS=${REQUIRE_OCR_TOOLS}"

gcloud run jobs deploy "${JOB_NAME}" \
  --project="${GCP_PROJECT_ID}" \
  --region="${GCP_REGION}" \
  --image="${IMAGE_URI}" \
  --command="npm" \
  --args="run,start:job" \
  --tasks=1 \
  --parallelism=1 \
  --task-timeout="${TASK_TIMEOUT}" \
  --max-retries="${MAX_RETRIES}" \
  --set-env-vars="${ENV_VARS}"

echo "Deployed Cloud Run Job: ${JOB_NAME}"
